name: Build Project

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Register
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Test application with npm
        if: ${{ github.event_name == 'push' }}
        run: |
          npm ci
          npm run-script test

      - name: Build application with npm
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          npm ci
          npm run-script build
      - name: Build docker image
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          # Set the context to use the current directory and not execute it's own git checkout.
          context: .
          push: false
