# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Docker Hub Publish

on:
  release:
    types: [released]

jobs:
  push_to_registry:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build application with npm
        run: npm ci && npm run-script build
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lfenergycompas/compas-open-scd:${GITHUB_REF##*/} lfenergycompas/compas-open-scd:latest
