name: Test
on:
  push:
    branches-ignore:
      - main
    paths:
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install and Test
        run: |
          npm i @nx/nx-linux-x64-gnu
          npm clean-install
          npx playwright install chromium --with-deps
          cd packages/compas-open-scd
          npm run-script test
